[directory]
truncation_length = 4
truncation_symbol = 'â€¦/'

[directory.substitutions]
"Documents" = "ï…œ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
"Videos" = "ï€½ "
"/mnt/auto/buho/remote/proyectos" = "ğŸ—ï¸ ğŸ¦‰"
"/mnt/auto/buho/remote" = "ğŸ¦‰" 
"/mnt/auto/nuc/remote" = "ğŸ‘¾"

[nodejs]
detect_extensions = []

[custom.home]
when = ''' test "$HOME" = "$PWD" '''
style = "bold cyan"
#symbol = 'ï€• '
symbol = 'ğŸ  '
format = '[$symbol]($style)'

[java]
disabled = true
[lua]
disabled = true

